# Generated by Django 4.2.7 on 2026-01-01 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('plinko', 'Plinko'), ('slots', 'Slots'), ('wheel', 'Wheel'), ('cards', 'Cards'), ('mining', 'Mining')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('maintenance_message', models.TextField(default='Game is under maintenance. Please try again later.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Game statuses',
                'db_table': 'game_statuses',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('plinko', 'Plinko'), ('slots', 'Slots'), ('wheel', 'Wheel'), ('cards', 'Cards'), ('mining', 'Mining')], max_length=20)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss')], max_length=10)),
                ('multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('points_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('game_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='users.user')),
            ],
            options={
                'db_table': 'game_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
