# Generated by Django 4.2.7 on 2026-01-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('crash', 'Crash'), ('limbo', 'Limbo'), ('slots', 'Slots'), ('cards', 'Cards'), ('mining', 'Mining')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gamestatus',
            name='game_type',
            field=models.CharField(choices=[('crash', 'Crash'), ('limbo', 'Limbo'), ('slots', 'Slots'), ('cards', 'Cards'), ('mining', 'Mining')], max_length=20, unique=True),
        ),
    ]
